In [1]:
import numpy as np
# Generate a random matrix
np.random.seed(42) # for reproducibility
A = np.random.randint(0, 10, size=(3, 2))
# Apply SVD
U, S, VT = np.linalg.svd(A)
# Convert singular values to diagonal matrix
Sigma = np.diag(S)
# Reconstruct the matrix
A_reconstructed = U[:, :2] @ Sigma @ VT
# Display results
print("Random Matrix A:\n", A)
print("\nU Matrix:\n", U)
print("\nSigma Matrix:\n", Sigma)
print("\nV Transpose Matrix:\n", VT)
print("\nReconstructed Matrix:\n", A_reconstructed)

Random Matrix A:
 [[6 3]
 [7 4]
 [6 9]]

U Matrix:
 [[-0.44037872 -0.51754229 -0.73363244]
 [-0.53703416 -0.50298667  0.67719918]
 [-0.71948655  0.69220979 -0.05643326]]

Sigma Matrix:
 [[14.62124672  0.        ]
 [ 0.          3.63581413]]

V Transpose Matrix:
 [[-0.73307228 -0.68015074]
 [-0.68015074  0.73307228]]

Reconstructed Matrix:
 [[6. 3.]
 [7. 4.]
 [6. 9.]]
