In [2]:
import numpy as np
from sklearn.random_projection import GaussianRandomProjection
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

iris = load_iris()
x = iris.data
y = iris.target

print("Original Dataset Shape", x.shape)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,
random_state=42)

print("Training Shape", x_train.shape)
print("Testing Shape", x_test.shape)

random_proj = GaussianRandomProjection(n_components=3, random_state=42)
x_train_proj = random_proj.fit_transform(x_train)
x_test_proj = random_proj.transform(x_test)

print("\nProjected Training Shape", x_train_proj.shape)
print("Projected Testing Shape", x_test_proj.shape)

print("\nSample Projected Data (First 5 rows):\n")
print(np.round(x_train_proj[:5], 3))

original_dist = np.linalg.norm(x_train[0] - x_train[1])
projected_dist = np.linalg.norm(x_train_proj[0] - x_train_proj[1])

print("\nDistance Between First Two Points:")
print("Original Distance:", round(original_dist, 3))
print("Projected Distance:", round(projected_dist, 3))

print("\nProjection Matrix Shape:",random_proj.components_.shape)

Original Dataset Shape (150, 4)
Training Shape (120, 4)
Testing Shape (30, 4)

Projected Training Shape (120, 3)
Projected Testing Shape (30, 3)

Sample Projected Data (First 5 rows):

[[ 1.582 -0.108 -0.44 ]
 [ 2.196  0.18  -0.676]
 [ 4.55   3.307 -2.399]
 [ 1.879  0.439 -0.718]
 [ 1.668  0.246 -0.592]]

Distance Between First Two Points:
Original Distance: 1.463
Projected Distance: 0.718

Projection Matrix Shape: (3, 4)
